export default {
  subMenuBtn: document.querySelector('#sub-menu-btn'),
  subMenuMobileBtn: document.querySelector('#sub-menu-mobile-btn'),
  subMenuList: document.querySelector('.sub-menu-list'),
  subMenuMobileList: document.querySelector('.sub-menu-mobile-list'),
  bottomSvg: document.querySelector('.bottom'),
  topSvg: document.querySelector('.top'),
  mobileBottomSvg: document.querySelector('.mobile-bottom'),
  mobileTopSvg: document.querySelector('.mobile-top'),
  burgerBtn: document.querySelector('.burger-btn'),
  closeBtn: document.querySelector('.close-menu-btn'),
  navRef: document.querySelector('.navigation'),
  mobileNavRef: document.querySelector('.navigation-mobile'),
  sliderContent: document.querySelector('.slider-container'),
  prevBtn: document.querySelector('#prev-btn'),
  nextBtn: document.querySelector('#next-btn'),
  dotsContainer: document.querySelector('.dots-list'),
  mobileMenuContainer: document.querySelector('.mobile-menu'),
};
